apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app-deployment
  labels:
    app: cloud-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-app-pod
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cloud-app-pod
    spec:
      containers:
        - name: cloud-app-pod
          image: eliriat/cloud-app:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"