apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app-deployment
  labels:
    app: cloud-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-app-pod
  template:
    metadata:
      labels:
        app: cloud-app-pod
    spec:
      containers:
        - name: cloud-app-pod
          image: eliriat/cloud-app:latest
          ports:
            - containerPort: 8080